In [2]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [3]:
url = "https://www.worldometers.info/coronavirus/"
response = requests.get(url)

In [4]:
soup = BeautifulSoup(response.text, 'lxml')

In [5]:
n_columns = 0
n_rows=0
column_names = []

In [55]:
tableWorldometer = soup.find("table", {'id' : 'main_table_countries_today'})

In [56]:
for row in tableWorldometer.find_all('tr'):
    td_tags = row.find_all('td')
    if len(td_tags) > 0:
        n_rows+=1
    if n_columns == 0:
         n_columns = len(td_tags)
    th_tags = row.find_all('th')
    if len(th_tags) > 0 and len(column_names) == 0:
        for th in th_tags:
            column_names.append(th.get_text())
    if len(column_names) > 0 and len(column_names) != n_columns:
        raise Exception("Column titles do not match the number of columns")
    columns = column_names if len(column_names) > 0 else range(0,n_columns)
    df = pd.DataFrame(columns = columns,index= range(0,n_rows))
    row_marker = 0
    for row in tableWorldometer.find_all('tr'):
        column_marker = 0
        columns = row.find_all('td')
        for column in columns:
            df.iat[row_marker,column_marker] = column.get_text()
            column_marker += 1
        if len(columns) > 0:
            row_marker += 1

In [57]:
df = df.dropna()

In [45]:
import csv

In [46]:
df.to_csv('test.csv', sep=',')

In [60]:
df

,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,ActiveCases,"Serious,Critical",TotÂ Cases/1M pop,Deaths/1M pop,TotalTests,Tests/ 1M pop
0,World,"1,430,590","+84,554","82,025","+7,371","301,940","1,046,625","47,890",184,10.5,,
1,USA,"400,335","+33,331","12,841","+1,970","21,674","365,820","9,169","1,209",39,"2,075,739","6,271"
2,Spain,"141,942","+5,267","14,045",+704,"43,208","84,689","7,069","3,036",300,"355,000","7,593"
3,Italy,"135,586","+3,039","17,127",+604,"24,392","94,067","3,792","2,243",283,"755,445","12,495"
4,France,"109,069","+11,059","10,328","+1,417","19,337","79,404","7,131","1,671",158,"224,254","3,436"
5,Germany,"107,663","+4,288","2,016",+206,"36,081","69,566","4,895","1,285",24,"918,460","10,962"
6,Iran,"62,589","+2,089","3,872",+133,"27,039","31,678","3,987",745,46,"211,136","2,514"
7,UK,"55,242","+3,634","6,159",+786,135,"48,948","1,559",814,91,"266,694","3,929"
8,Turkey,"34,109","+3,892",725,+76,"1,582","31,802","1,474",404,9,"228,868","2,714"
9,Switzerland,"22,253",+596,821,+56,"8,704","12,728",391,"2,571",95,"167,429","19,346"
10,Belgium,"22,194","+1,380","2,035",+403,"4,157","16,002","1,260","1,915",176,"80,512","6,947"
11,Netherlands,"19,580",+777,"2,101",+234,250,"17,229","1,424","1,143",123,"86,589","5,053"
12,Canada,"17,897","+1,230",381,+58,"4,028","13,488",426,474,10,"346,507","9,181"
13,Brazil,"14,034","+1,851",686,+122,127,"13,221",296,66,3,"54,824",258
14,Austria,"12,639",+342,243,+23,"4,046","8,350",243,"1,403",27,"115,235","12,795"
15,Portugal,"12,442",+712,345,+34,184,"11,913",271,"1,220",34,"121,256","11,892"
16,S. Korea,"10,331",+47,192,+6,"6,694","3,445",55,202,4,"477,304","9,310"
17,Israel,"9,248",+344,65,+8,770,"8,413",149,"1,068",8,"117,339","13,557"
18,Sweden,"7,693",+487,591,+114,205,"6,897",640,762,59,"54,700","5,416"
19,Russia,"7,497","+1,154",58,+11,494,"6,945",8,51,0.4,"795,000","5,448"
20,Norway,"6,086",+221,89,+13,32,"5,965",78,"1,123",16,"113,896","21,009"
21,Australia,"5,988",+93,49,+4,"2,547","3,392",93,235,2,"310,700","12,184"
22,Ireland,"5,709",+345,210,+36,25,"5,474",165,"1,156",43,"42,484","8,604"
23,India,"5,311",+533,150,+14,421,"4,740",,4,0.1,"140,293",102
24,Chile,"5,116",+301,43,+6,898,"4,175",337,268,2,"57,122","2,988"
25,Denmark,"5,071",+390,203,+16,"1,491","3,377",127,875,35,"58,419","10,086"
26,Czechia,"5,017",+195,88,+10,172,"4,757",86,468,8,"91,247","8,521"
27,Poland,"4,848",+435,129,+22,191,"4,528",50,128,3,"92,215","2,437"
28,Romania,"4,417",+360,197,+21,460,"3,760",274,230,10,"43,578","2,265"
29,Pakistan,"4,035",+269,57,+4,429,"3,549",28,18,0.3,"39,183",177
...,...,...,...,...,...,...,...,...,...,...,...,...
183,Nepal,9,,,,1,8,,0.3,,"1,890",65
184,Montserrat,9,+3,,,,9,1,"1,803",,36,"7,212"
185,Malawi,8,+3,1,+1,,7,1,0.4,0.05,,
186,Turks and Caicos,8,,1,,,7,,207,26,61,"1,576"
187,CAR,8,,,,,8,,2,,,
188,St. Vincent Grenadines,8,+1,,,1,7,,72,,56,505
189,Somalia,8,+1,,,1,7,,0.5,,,
190,Belize,7,,1,,,6,1,18,3,268,674
191,Cabo Verde,7,,1,,1,5,,13,2,,
192,Vatican City,7,,,,,7,,"8,739",,,
193,Botswana,6,,1,,,5,,3,0.4,"1,154",491
194,Mauritania,6,,1,,2,3,,1,0.2,67,14
195,Nicaragua,6,,1,,,5,,0.9,0.2,,
196,St. Barth,6,,,,1,5,,607,,,
197,Sierra Leone,6,,,,,6,,0.8,,,
198,Bhutan,5,,,,2,3,,6,,"1,166","1,511"
199,Gambia,4,,1,,2,1,,2,0.4,,
200,Sao Tome and Principe,4,,,,,4,,18,,19,87
201,Western Sahara,4,,,,,4,,7,,,
202,Anguilla,3,,,,,3,,200,,,
203,British Virgin Islands,3,,,,,3,,99,,,
204,Burundi,3,,,,,3,,0.3,,,
205,Caribbean Netherlands,2,,,,,2,,76,,10,381
206,Falkland Islands,2,,,,,2,,575,,,
207,Papua New Guinea,2,,,,,2,,0.2,,72,8
208,South Sudan,2,+1,,,,2,,0.2,,,
209,Saint Pierre Miquelon,1,,,,,1,,173,,,
210,Timor-Leste,1,,,,,1,,0.8,,,
211,China,"81,802",+62,"3,333",+2,"77,279","1,190",189,57,2,,
212,Total:,"1,430,590","+84,554","82,025","+7,371","301,940","1,046,625","47,890",183.5,10.5,,